apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: taxcalc
  namespace: argocd
spec:
  description: Taxcalc GitOps project scoped to taxcalc-config and taxcalc-dev
  sourceRepos:
    - https://github.com/AI-Native-2026-07-29-Intuit/shradha-hirve-taxcalc-config.git
  destinations:
    - namespace: taxcalc-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: networking.k8s.io
      kind: Ingress
