apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taxcalc-prod
resources:
  - ../../base
replicas:
  - name: taxcalc-api
    count: 3
images:
  - name: uptimecrew/taxcalc-api
    newName: uptimecrew/taxcalc-api
    newTag: "0.1.0"
patches:
  - target:
      kind: ConfigMap
      name: taxcalc-api-config
    patch: |-
      - op: replace
        path: /data/SPRING_PROFILES_ACTIVE
        value: "prod"
      - op: add
        path: /data/LOG_LEVEL
        value: "WARN"
      - op: replace
        path: /data/SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://postgres.taxcalc-prod.svc.cluster.local:5432/taxcalc_dev"
      - op: replace
        path: /data/SPRING_DATA_REDIS_HOST
        value: "redis.taxcalc-prod.svc.cluster.local"
      - op: replace
        path: /data/SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: "kafka.taxcalc-prod.svc.cluster.local:9092"
      - op: replace
        path: /data/SPRING_DATA_MONGODB_URI
        value: "mongodb://mongo.taxcalc-prod.svc.cluster.local:27017/taxcalc"
      - op: replace
        path: /data/OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector.taxcalc-prod.svc.cluster.local:4318"
  - target:
      kind: StatefulSet
      name: kafka
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: "PLAINTEXT://kafka.taxcalc-prod.svc.cluster.local:9092"
  - target:
      kind: HorizontalPodAutoscaler
      name: taxcalc-api
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
  - target:
      kind: Deployment
      name: taxcalc-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
