apiVersion: v1
kind: Secret
metadata:
  name: taxcalc-api-secrets
  namespace: taxcalc-dev
  labels:
    app.kubernetes.io/name: taxcalc-api
    app.kubernetes.io/part-of: taxcalc
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: api
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "replace-at-apply-time-from-secrets-manager"
