apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-quota-and-limits.yaml
  - 05-platform-dependencies.yaml
  - 10-taxcalc-api.deployment.yaml
  - 20-taxcalc-api.service.yaml
  - 30-taxcalc-api.configmap.yaml
  - 40-taxcalc-api.secret.yaml
  - 50-taxcalc-api.hpa.yaml
  - 60-taxcalc-api.ingress.yaml
